### PR TITLE
added keyword arguments for models

### PR DESCRIPTION
**Pull request by AliAbadiHub**
tried to not alter any other code. vscode kept adding stuff on save, so i made these changes on github directly in the browser

### CODE REVIEW

**Comment by gkamradt** [comment]
@AliAbadiHub I'm seeing that LangChain doesn't use the model_kwargs convention

https://python.langchain.com/docs/modules/model_io/models/chat.html

What's the reason for the change?

**Comment by AliAbadiHub** [comment]
That's so strange it wouldn't work on jupyterlab locally without it. I'll take down the PR.

**Comment by gkamradt** [comment]
Cool sounds good - thank you for the edit in the first place. Have a good day!

**Comment by AliAbadiHub** [comment]
Likewise!

**Pull request closed without merging**
